version: '3.4'

services:
  blockbuster:
    container_name: blockbuster
    image: ${DOCKER_REGISTRY-}blockbuster
    build:
      context: .
      dockerfile: Blockbuster/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest # Use the desired SQL Server version
    container_name: blockbuster-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql # Persistent SQL Server data
      - ./sql:/var/opt/sqlscripts # Mount the directory containing init.sql and cookie.sql
    ports:
      - "1433:1433" # Default SQL Server port
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -d master -i /var/opt/sqlscripts/application_db_context.sql
        wait


volumes:
  sql_data:
    driver: local
  data_protection_keys:
    driver: local
